#!/system/bin/sh

function click() {
    input tap $1 $2 1>/dev/null 2>&1
}
i=0
while [ 1 ];do
    ((i++))
    if ((i >= 1000000));then
        i=0;
    fi
    if [ -a "/sdcard/000/mxd" ];then
        # click 950 460 #普通攻击 执行间隔344ms
        dd if=/sdcard/000/recordtap of=/dev/input/event3 $2 1>/dev/null 2>&1
        sleep 0.3
        if ((i%436 == 0));then
            sleep 1
            click 1380 600 #key5
        fi
        if ((i%900 == 0));then
            sleep 1
            click 1530 670 #key3
        fi
        if ((i%150 == 0));then
            sleep 1
            click 1380 770 #key2
        fi
        if ((i%3200 == 0));then
            sleep 1
            click 1700 630 #key4
            sleep 1
            click 950 800 #断网确认键
        fi
    else
        sleep 3
    fi
done
