#!/system/bin/sh

function click() {
    input tap $1 $2 1>/dev/null 2>&1
}
i=0
while [ 1 ];do
    ((i++))
    if ((i >= 1000000));then
        i=0;
    fi
    sleep 3
    if [ -a "/sdcard/000/mxd" ];then
        if ((i%30 == 0));then
            click 80 400 #auto
            sleep 1
            click 1700 630 #key4
            sleep 1
            click 80 400 #auto
            sleep 1
        fi
        click 1290 930 #key1
    fi
done
