#!/system/bin/sh

function click() {
    input tap $1 $2 1>/dev/null 2>&1
}
i=0
while [ 1 ];do
    ((i++))
    if ((i >= 1000000));then
        i=0;
    fi
    if [ -a "/sdcard/000/mxd" ];then
        click 1780 850 #普通攻击
        if ((i%120 == 0));then
            sleep 0.5
            click 730 320 #key5
        fi
        if ((i%250 == 0));then
            sleep 0.5
            click 820 370 #key3
        fi
        if ((i%30 == 0));then
            sleep 0.5
            click 740 420 #key2
        fi
        if ((i%380 == 0));then
            sleep 0.5
            click 910 340 #key4
        fi
    else
        sleep 3
    fi
done
