#!/system/bin/sh

function click() {
    input tap $1 $2 1>/dev/null 2>&1
}
i=0
turn="right"
skill="one"
while [ 1 ];do
    ((i++))
    if ((i >= 1000000));then
        i=0;
    fi
    sleep 0.1
    if [ -a "/sdcard/000/mxd" ];then
        if ((i%30 == 0));then
            if [ "$turn" = "right" ];then
                turn="left"
                click 80 570 #左移
            else
                turn="right"
                click 240 570 #右移
            fi
            continue
        fi
        if ((i%10 == 0));then
            if [ "$skill" = "one" ];then
                skill="two"
                click 920 520 #key2
            else
                skill="one"
                click 920 400 #key5
            fi
            continue
        fi
        click 1180 550 #普通攻击
    fi
done
