#!/bin/bash

function click() {
    adb shell input tap $1 $2 1>/dev/null 2>&1
}
# 电脑
# click 870 620 #key1
# click 920 520 #key2
# click 1020 440 #key3
# click 1135 430 #key4
# click 920 400 #key5
# click 1020 330 #key6
# click 1135 300 #key7
# click 60 260 #auto
# click 1180 550 #普通攻击
# click 1020 640 #跳跃
# click 80 570 #左移
# click 240 570 #右移
function playWithComputer() {
    adb connect localhost:6555
    i=0
    while [ 1 ];do
        ((i++))
        if ((i >= 1000000));then
            i=0;
        fi
        sleep 3
        if ((i%20 == 0));then
            click 60 260 #auto
            sleep 0.5
            click 1135 430 #key4
            sleep 0.5
            click 60 260 #auto
            sleep 0.5
        fi
        click 870 620 #key1
    done
}
# 手机
# click 1290 930 #key1
# click 1380 770 #key2
# click 1530 670 #key3
# click 1700 630 #key4
# click 1380 600 #key5
# click 1530 490 #key6
# click 1700 450 #key7
# click 80 400 #auto
# click 1780 840 #普通攻击
# click 1480 950 #跳跃
# click 120 850 #左移
# click 360 850 #右移
function playWithPhone() {
    i=0
    while [ 1 ];do
        ((i++))
        if ((i >= 1000000));then
            i=0;
        fi
        sleep 3
        if ((i%20 == 0));then
            click 80 400 #auto
            sleep 0.5
            click 1700 630 #key4
            sleep 0.5
            click 80 400 #auto
            sleep 0.5
        fi
        click 1290 930 #key1
    done
}
if [ -n "$1" ];then
    playWithComputer
else
    playWithPhone
fi
