#!/bin/bash

if [ "$1" = "-h" ];then
    echo ./run 加蓝时间[default: 20] 加血时间[default: 80]
    exit
fi

a=${1-20}
b=${2-80}

echo 加蓝时间: $a 加血时间: $b

expect -c "
set timeout 30000;
spawn adb shell;
expect {
    \"*\$*\" {send \"cd /sdcard/000\rsh stop\recho \\\"a=${a};b=${b}\\\" > param\rnohup sh start &\rexit\r\"}
}
interact
"
