#!/bin/bash

export PATH=$PATH:/root/tools/node/bin:/root/tools/mongodb/bin
export DIR=/root/main

#检查pid是否存在
function check_pid_start() {
    local name command count
    name="$1";command="$2";
    count=`ps -A|grep "\<${name}\>"|wc -l`
    if [ 0 == ${count} ];then
        echo "start ${name}"
        ${command}
    else
        echo "${name} already started"
    fi
}

#检查pm2工程是否存在
function check_pm2_start() {
    local name id
    name="$1";
    id=`pm2 id ${name}|sed 's/]\|\[\| //g'`
    if [ -z "${id}" ];then
        echo "start ${name} with pm2"
        pushd ${DIR}/${name}
        pm2 start "app.js" --name ${name}
        popd
    else
        echo "${name} already started"
    fi
}

#检查java工程是否存在
function check_java_start() {
    local dir name count
    dir="$1";name="$2";
    count=`ps -ef |grep java|grep "\<$name\>"|wc -l`
    if [ $count != 0 ];then
        echo "$dir/$name is running"
    else
        prefix=$(date '+%Y-%m-%d-%H-%M-%S')
        pushd $dir
        ls log|xargs -I bbbb mv log/bbbb log/.bbbb
        echo "$dir/$name is starting..."
        echo "nohup java -jar $name start > log/${prefix}.log &"
        nohup java -jar $name start > log/${prefix}.log 2>&1 &
        popd
    fi
}

#启动mysqld
function start_mysqld() {
    service mysqld start
}

#启动mongodb
function start_mongodb() {
    mkdir -p /root/database/mongodb/logs
    mkdir -p /root/database/mongodb/db
    /root/tools/mongodb/bin/mongod -f /root/database/mongodb/mongodb.conf
}

#启动nginx
function start_nginx() {
    mkdir -p /root/main/nginx/logs
    nginx -p /root/main/nginx -c config/nginx.conf
}

# common
echo check_pid_start mysqld start_mysqld
check_pid_start mysqld start_mysqld
echo check_pid_start mongod start_mongodb
check_pid_start mongod start_mongodb
echo check_pid_start nginx start_nginx
check_pid_start nginx start_nginx
sleep 3

# 官网
mkdir -p /root/main/OWServer/download/apps/OWServer
mkdir -p /root/main/OWServer/download/apps/OWHome_PC
echo check_pm2_start OWServer
check_pm2_start OWServer
echo check_pm2_start OWHome_PC
check_pm2_start OWHome_PC

# plate
mkdir -p /root/main/SPServer/log
mkdir -p /root/main/SPServer/download/apps/SPServer
mkdir -p /root/main/SPServer/download/apps/SPImage
mkdir -p /root/main/SPServer/download/apps/SPPolice_PC
mkdir -p /root/main/SPServer/download/apps/SPPolice
mkdir -p /root/main/SPServer/download/apps/OWHome_PC
echo check_java_start SPServer spserver.war
check_java_start SPServer spserver.war
echo check_pm2_start SPPolice_PC
check_pm2_start SPPolice_PC
echo check_pm2_start SPImage
check_pm2_start SPImage

# city
mkdir -p /root/main/SCServer/log
mkdir -p /root/main/SCServer/download/apps/SCServer
mkdir -p /root/main/SCServer/download/apps/SCPolice_PC
echo check_java_start SCServer scserver.war
check_java_start SCServer scserver.war
echo check_pm2_start SCPolice_PC
check_pm2_start SCPolice_PC

# data
mkdir -p /root/main/SDServer/download/apps/SDServer
mkdir -p /root/main/SDServer/download/apps/SDPolice_PC
echo check_pm2_start SDServer
check_pm2_start SDServer
echo check_pm2_start SDPolice_PC
check_pm2_start SDPolice_PC

# file
mkdir -p /root/main/SLServer/download/apps/SLServer
mkdir -p /root/main/SLServer/download/apps/SLPolice_PC
echo check_pm2_start SLServer
check_pm2_start SLServer
echo check_pm2_start SLPolice_PC
check_pm2_start SLPolice_PC
